import React, { createContext, useContext, useState, useEffect } from 'react';

// Translations
const translations = {
  en: {
    "Home": "Home",
    "Properties": "Properties",
    "Vehicles": "Vehicles",
    "Jobs": "Jobs",
    "Academy": "Academy",
    "Professionals": "Professionals",
    "About": "About",
    "Contact": "Contact",
    "Browse Properties": "Browse Properties",
    "Menu": "Menu",
    "Language": "Language",
    "Currency": "Currency",
    "Switch to Dark": "Switch to Dark",
    "Switch to Light": "Switch to Light",
    "My Dashboard": "My Dashboard",
    "Account": "Account",
    "Login": "Login",
    "Sign In": "Sign In",
    "Join Us": "Join Us",
    // MegaMenu content
    "Residential": "Residential",
    "Houses": "Houses",
    "Apartments": "Apartments",
    "Villas": "Villas",
    "Commercial": "Commercial",
    "Land": "Land",
    "Offices": "Offices",
    "Warehouses": "Warehouses",
    "Rental": "Rental",
    "Rentals": "Rentals",
    "Furnished": "Furnished",
    "Cars": "Cars",
    "SUVs": "SUVs",
    "Trucks": "Trucks",
    "Motorcycles": "Motorcycles",
    "Heavy Machinery": "Heavy Machinery",
    "Legal Experts": "Legal Experts",
    "Valuators": "Valuators",
    "Consultants": "Consultants",
    "Brokers": "Brokers",
    "WhatsApp Support": "WhatsApp Support",
    "EN": "EN",
    "SOM": "SOM",
    "USD": "USD",
    "ETB": "ETB",
    
    // Agreements page translations
    "Agreement Registry & Legal Documentation": "Agreement Registry & Legal Documentation",
    "Create, preview, print, and submit secure legal agreements for verification on AmaanEstate.": "Create, preview, print, and submit secure legal agreements for verification on AmaanEstate.",
    "STEP 1 - Selecting Agreement Scheme": "STEP 1 - Selecting Agreement Scheme",
    "Select Agreement Type": "Select Agreement Type",
    "Property Sale Agreement": "Property Sale Agreement",
    "Property Rental Agreement": "Property Rental Agreement",
    "Vehicle Sale Agreement": "Vehicle Sale Agreement",
    "Vehicle Rental Agreement": "Vehicle Rental Agreement",
    "Broker Commission Agreement": "Broker Commission Agreement",
    "Agreement Covenant Details": "Agreement Covenant Details",
    "Section D: Subject Asset Specifications": "Section D: Subject Asset Specifications",
    "Section E: Covenant Legal Clauses": "Section E: Covenant Legal Clauses",
    "Agreement Title *": "Agreement Title *",
    "Deed Transaction Date *": "Deed Transaction Date *",
    "Currency Unit *": "Currency Unit *",
    "Default Asset Price Type *": "Default Asset Price Type *",
    "Party A (Grantor / Owner)": "Party A (Grantor / Owner)",
    "Full Legal Name *": "Full Legal Name *",
    "Contact Phone *": "Contact Phone *",
    "Email Address": "Email Address",
    "National ID Card Number": "National ID Card Number",
    "Domicile / Address *": "Domicile / Address *",
    "Party A Binding Endorsement Signature": "Party A Binding Endorsement Signature",
    "Party B Binding Endorsement Signature": "Party B Binding Endorsement Signature",
    "Witness Verification Section": "Witness Verification Section",
    "Witness 1": "Witness 1",
    "Witness 2": "Witness 2",
    "Witness 3": "Witness 3",
    "Witness 1 Full Name *": "Witness 1 Full Name *",
    "Witness 2 Full Name *": "Witness 2 Full Name *",
    "Witness 3 Full Name *": "Witness 3 Full Name *",
    "Witness 1 Binding Endorsement Signature": "Witness 1 Binding Endorsement Signature",
    "Witness 2 Binding Endorsement Signature": "Witness 2 Binding Endorsement Signature",
    "Witness 3 Binding Endorsement Signature": "Witness 3 Binding Endorsement Signature",
    "Witnesses": "Witnesses",
    "Witness 1: Full Name + Signature": "Witness 1: Full Name + Signature",
    "Witness 2: Full Name + Signature": "Witness 2: Full Name + Signature",
    "Witness 3: Full Name + Signature": "Witness 3: Full Name + Signature",
    "Witness 1 must type in their binding signature name.": "Witness 1 must type in their binding signature name.",
    "Witness 2 must type in their binding signature name.": "Witness 2 must type in their binding signature name.",
    "Witness 3 must type in their binding signature name.": "Witness 3 must type in their binding signature name.",
    "Type Witness 1 Full Name *": "Type Witness 1 Full Name *",
    "Type Witness 2 Full Name *": "Type Witness 2 Full Name *",
    "Type Witness 3 Full Name *": "Type Witness 3 Full Name *",
    "Type Signature": "Type Signature",
    "Draw Signature": "Draw Signature",
    "Type Full Name for Digital Script *": "Type Full Name for Digital Script *",
    "Type name here (e.g. Abdirahman Yusuf)": "Type name here (e.g. Abdirahman Yusuf)",
    "Type name here (e.g. Halima Ahmed)": "Type name here (e.g. Halima Ahmed)",
    "Draw inside the dark pad below": "Draw inside the dark pad below",
    "Reset Canvas": "Reset Canvas",
    "Party B (Grantee / Client)": "Party B (Grantee / Client)",
    "Property Code / Identifier": "Property Code / Identifier",
    "Property Name / Core Title *": "Property Name / Core Title *",
    "Category Range": "Category Range",
    "Structure Form (Apartment, Land Plot, etc)": "Structure Form (Apartment, Land Plot, etc)",
    "Metropolis City *": "Metropolis City *",
    "Administrative District": "Administrative District",
    "Exchange Valuation Price ({currency}) *": "Exchange Valuation Price ({currency}) *",
    "Payment Instalments / Terms Description": "Payment Instalments / Terms Description",
    "Covenant Stipulations *": "Covenant Stipulations *",
    "Vehicle ID / Chassis Ref": "Vehicle ID / Chassis Ref",
    "Automobile Manufacturer (Make) *": "Automobile Manufacturer (Make) *",
    "Model Name *": "Model Name *",
    "Production Year": "Production Year",
    "Official License Plate *": "Official License Plate *",
    "Agreed Car Valuation Price ({currency}) *": "Agreed Car Valuation Price ({currency}) *",
    "Broker Commission Terms & Compensations *": "Broker Commission Terms & Compensations *",
    "e.g. Abdirahman Yusuf": "e.g. Abdirahman Yusuf",
    "e.g. Halima Ahmed": "e.g. Halima Ahmed",
    "e.g. +252 61 5XXXXXX": "e.g. +252 61 5XXXXXX",
    "e.g. +252 61 7XXXXXX": "e.g. +252 61 7XXXXXX",
    "e.g. partyA@example.com": "e.g. partyA@example.com",
    "e.g. partyB@example.com": "e.g. partyB@example.com",
    "e.g. NID-842719": "e.g. NID-842719",
    "e.g. NID-108259": "e.g. NID-108259",
    "e.g. Mogadishu Airport Zone, Wadajir, Somalia": "e.g. Mogadishu Airport Zone, Wadajir, Somalia",
    "e.g. Hodan District, Mogadishu, Somalia": "e.g. Hodan District, Mogadishu, Somalia",
    "e.g. AP-94021": "e.g. AP-94021",
    "e.g. Luxury Penthouse Suite B-2": "e.g. Luxury Penthouse Suite B-2",
    "e.g. Duplex Villa": "e.g. Duplex Villa",
    "e.g. Mogadishu": "e.g. Mogadishu",
    "e.g. Hodan": "e.g. Hodan",
    "e.g. 185000": "e.g. 185000",
    "e.g. 30% Down, 70% Bank Escrow Transfer": "e.g. 30% Down, 70% Bank Escrow Transfer",
    "e.g. CHASSIS-N028741": "e.g. CHASSIS-N028741",
    "e.g. Toyota": "e.g. Toyota",
    "e.g. Land Cruiser": "e.g. Land Cruiser",
    "e.g. JUBALAND-840": "e.g. JUBALAND-840",
    "e.g. 52000": "e.g. 52000",
    "Provide description of broker duties, affiliated real estate listings, payment percentages, and conditional terms...": "Provide description of broker duties, affiliated real estate listings, payment percentages, and conditional terms...",
    "Cancel": "Cancel",
    "Preview Agreement": "Preview Agreement",
    "Download QR Code": "Download QR Code",
    "Submit for Approval": "Submit for Approval",
    "Back to Edit": "Back to Edit",
    "Print": "Print",
    "Download PDF": "Download PDF",
    "Verification Constraints Required:": "Verification Constraints Required:",
    "Submitted Successfully": "Submitted Successfully",
    "Status: Pending Approval": "Status: Pending Approval",
    "System Record Registered": "System Record Registered",
    "Agreement Record ID": "Agreement Record ID",
    "Audit Track Status": "Audit Track Status",
    "Pending Officer Review": "Pending Officer Review",
    "Your legal agreement documents have been logged securely. You can direct the municipal administration division or real estate desk in charge of verification to sign off using the administrator console.": "Your legal agreement documents have been logged securely. You can direct the municipal administration division or real estate desk in charge of verification to sign off using the administrator console.",
    "Go to Dashboard": "Go to Dashboard",
    "Draft Another Agreement": "Draft Another Agreement",
    "Cursive Representation": "Cursive Representation",
    "Vectored path captured. Ready to bind.": "Vectored path captured. Ready to bind.",
    "DRAFT DOCUMENT - PREVIEW STATE": "DRAFT DOCUMENT - PREVIEW STATE",
    "LEDGER REGISTRY DEED": "LEDGER REGISTRY DEED",
    "Provisional Draft": "Provisional Draft",
    "Witnessed & Logged on the secure AmaanEstate Administrative Grid on:": "Witnessed & Logged on the secure AmaanEstate Administrative Grid on:",
    "I. Contract Category Specifications": "I. Contract Category Specifications",
    "Deed Scheme Type:": "Deed Scheme Type:",
    "Current Valuation Total:": "Current Valuation Total:",
    "II. Contracting Sovereign Parties": "II. Contracting Sovereign Parties",
    "PARTY A (Grantor/Seller)": "PARTY A (Grantor/Seller)",
    "PARTY B (Grantee/Client)": "PARTY B (Grantee/Client)",
    "Name:": "Name:",
    "Phone:": "Phone:",
    "Email:": "Email:",
    "Registry ID No:": "Registry ID No:",
    "Domicile:": "Domicile:",
    "III. Object Asset Specifications": "III. Object Asset Specifications",
    "Property Unique ID:": "Property Unique ID:",
    "Property Title/Lodge:": "Property Title/Lodge:",
    "Covenant Status:": "Covenant Status:",
    "Structure Specification:": "Structure Specification:",
    "Metropolis City:": "Metropolis City:",
    "District Address:": "District Address:",
    "Vehicle Tracker No:": "Vehicle Tracker No:",
    "Automobile Maker:": "Automobile Maker:",
    "Model / Specific:": "Model / Specific:",
    "Manufacturing Year:": "Manufacturing Year:",
    "Registration Plate:": "Registration Plate:",
    "IV. General Legal Covenants & Assurances": "IV. General Legal Covenants & Assurances",
    "V. Binding Endorsements & Proof of Intent": "V. Binding Endorsements & Proof of Intent",
    "PARTY A SIGNATURE": "PARTY A SIGNATURE",
    "PARTY B SIGNATURE": "PARTY B SIGNATURE",
    "Blank Drawn Signature": "Blank Drawn Signature",
    "VI. Digital Registry Ledger Verification": "VI. Digital Registry Ledger Verification",
    "Deed Record ID:": "Deed Record ID:",
    "Contract Number:": "Contract Number:",
    "Registered Date:": "Registered Date:",
    "Verification Scheme:": "Verification Scheme:",
    "AmaanEstate Secured Cryptographic Ledger": "AmaanEstate Secured Cryptographic Ledger",
    "Provisional Registry (Pending Approval)": "Provisional Registry (Pending Approval)",
    "Agreement Title is required.": "Agreement Title is required.",
    "Party A (Seller/Owner) Full Name is required.": "Party A (Seller/Owner) Full Name is required.",
    "Party A Contact Phone is required.": "Party A Contact Phone is required.",
    "Party B (Buyer/Tenant) Full Name is required.": "Party B (Buyer/Tenant) Full Name is required.",
    "Party B Contact Phone is required.": "Party B Contact Phone is required.",
    "Property Name/Title is required.": "Property Name/Title is required.",
    "Property City is required.": "Property City is required.",
    "A valid property valuation price is required.": "A valid property valuation price is required.",
    "Vehicle Automobile Make and Model are required.": "Vehicle Automobile Make and Model are required.",
    "Vehicle License Plate is required.": "Vehicle License Plate is required.",
    "A valid vehicle transaction price is required.": "A valid vehicle transaction price is required.",
    "Broker Details / Commission Terms cannot be blank.": "Broker Details / Commission Terms cannot be blank.",
    "Party A must type in their binding signature name.": "Party A must type in their binding signature name.",
    "Party B must type in their binding signature name.": "Party B must type in their binding signature name.",
    "Review and alter standard legal protections directly inside the document. Ensure exact payment deadlines and breach guidelines are specified according to local commerce bylaws.": "Review and alter standard legal protections directly inside the document. Ensure exact payment deadlines and breach guidelines are specified according to local commerce bylaws."
  },
  so: {
    "Home": "Bogga Hore",
    "Properties": "Guryaha",
    "Vehicles": "Gaadiidka",
    "Jobs": "Shaqooyinka",
    "Academy": "Akadeemiyada",
    "Professionals": "Xirfadlayaasha",
    "About": "Ku Saabsan",
    "Contact": "Xiriir",
    "Browse Properties": "Baadh Guryaha",
    "Menu": "Tusaha",
    "Language": "Luqadda",
    "Currency": "Lacagta",
    "Switch to Dark": "Mawduuca Madoow",
    "Switch to Light": "Mawduuca Iftiinka",
    "My Dashboard": "Pankeeyga",
    "Account": "Koontada",
    "Login": "Gal",
    "Sign In": "Gal",
    "Join Us": "Nagu Soo Biir",
    "Residential": "Hooys Degaan",
    "Houses": "Guryaha",
    "Apartments": "Abaartamaano",
    "Villas": "Fillooyin",
    "Commercial": "Ganacsi",
    "Land": "Dhul",
    "Offices": "Xafiisyo",
    "Warehouses": "Bakaaro",
    "Rental": "Kiro",
    "Rentals": "Kirooyin",
    "Furnished": "Alaabeysan",
    "Cars": "Gawaarida",
    "SUVs": "Gawaarida Waaweyn",
    "Trucks": "Gawaarida Xamuulka",
    "Motorcycles": "Mootooyin",
    "Heavy Machinery": "Cagaf-Cagaf",
    "Legal Experts": "Khubaro Sharci",
    "Valuators": "Qiimayaal",
    "Consultants": "Lataliyayaal",
    "Brokers": "Dillaaliin",
    "WhatsApp Support": "Taageerada WhatsApp",
    "EN": "Ingiriis (EN)",
    "SOM": "Soomaali (SOM)",
    "USD": "Doolar (USD)",
    "ETB": "Birr (ETB)",
    
    // Agreements page translations in Somali
    "Agreement Registry & Legal Documentation": "Diiwaanka Heshiisyada & Dukumentiyada Sharciga",
    "Create, preview, print, and submit secure legal agreements for verification on AmaanEstate.": "Abuur, horay-u-eeg, daabac, oo u gudbi heshiisyo sharci oo sugan si loogu xaqiijiyo AmaanEstate.",
    "STEP 1 - Selecting Agreement Scheme": "TALLAABADA 1 - Doorashada Nooca Heshiiska",
    "Select Agreement Type": "Dooro Nooca Heshiiska",
    "Property Sale Agreement": "Heshiiska Iibka Hantida",
    "Property Rental Agreement": "Heshiiska Kireynta Hantida",
    "Vehicle Sale Agreement": "Heshiiska Iibka Gaadhiga",
    "Vehicle Rental Agreement": "Heshiiska Kireynta Gaadhiga",
    "Broker Commission Agreement": "Heshiiska Guddiga Dillaalka",
    "Agreement Covenant Details": "Faahfaahinta Heshiiska",
    "Section D: Subject Asset Specifications": "Qaybta D: Faahfaahinta Hantida Heshiiska",
    "Section E: Covenant Legal Clauses": "Qaybta E: Qodobada Sharciga ah ee Heshiiska",
    "Agreement Title *": "Cinwaanka Heshiiska *",
    "Deed Transaction Date *": "Taariikhda Heshiiska *",
    "Currency Unit *": "Nooca Lacagta *",
    "Default Asset Price Type *": "Nooca Qiimaha Hantida *",
    "Party A (Grantor / Owner)": "Dhinaca A (Bixiyaha / Mulkiilaha)",
    "Full Legal Name *": "Magaca Sharciga ah oo Dhammaystiran *",
    "Contact Phone *": "Khadka Taleefanka *",
    "Email Address": "Imeelka",
    "National ID Card Number": "Lambarka Aqoonsiga Qaranka",
    "Domicile / Address *": "Degganaanshaha / Cinwaanka *",
    "Party A Binding Endorsement Signature": "Saxeexa Adag ee Dhinaca A",
    "Party B Binding Endorsement Signature": "Saxeexa Adag ee Dhinaca B",
    "Witness Verification Section": "Qaybta Xaqiijinta Markhaatiga",
    "Witness 1": "Markhaati 1",
    "Witness 2": "Markhaati 2",
    "Witness 3": "Markhaati 3",
    "Witness 1 Full Name *": "Magaca oo Dhamaystiran ee Markhaatiga 1 *",
    "Witness 2 Full Name *": "Magaca oo Dhamaystiran ee Markhaatiga 2 *",
    "Witness 3 Full Name *": "Magaca oo Dhamaystiran ee Markhaatiga 3 *",
    "Witness 1 Binding Endorsement Signature": "Saxeexa Adag ee Markhaatiga 1",
    "Witness 2 Binding Endorsement Signature": "Saxeexa Adag ee Markhaatiga 2",
    "Witness 3 Binding Endorsement Signature": "Saxeexa Adag ee Markhaatiga 3",
    "Witnesses": "Markhaatiyada",
    "Witness 1: Full Name + Signature": "Markhaati 1: Magaca + Saxiix",
    "Witness 2: Full Name + Signature": "Markhaati 2: Magaca + Saxiix",
    "Witness 3: Full Name + Signature": "Markhaati 3: Magaca + Saxiix",
    "Witness 1 must type in their binding signature name.": "Markhaatiga 1 waa inuu ku qoraa magaca saxeexa ee khasabka ah.",
    "Witness 2 must type in their binding signature name.": "Markhaatiga 2 waa inuu ku qoraa magaca saxeexa ee khasabka ah.",
    "Witness 3 must type in their binding signature name.": "Markhaatiga 3 waa inuu ku qoraa magaca saxeexa ee khasabka ah.",
    "Type Witness 1 Full Name *": "Ku qor Magaca oo Dhamaystiran ee Markhaatiga 1 *",
    "Type Witness 2 Full Name *": "Ku qor Magaca oo Dhamaystiran ee Markhaatiga 2 *",
    "Type Witness 3 Full Name *": "Ku qor Magaca oo Dhamaystiran ee Markhaatiga 3 *",
    "Type Signature": "Ku Qor Saxeexa",
    "Draw Signature": "Ku Sawir Saxeexa",
    "Type Full Name for Digital Script *": "Ku qor magacaaga oo buuxa saxeexa dhijitaalka ah *",
    "Type name here (e.g. Abdirahman Yusuf)": "Halkan ku qor magaca (tusaale: Cabdiraxmaan Yuusuf)",
    "Type name here (e.g. Halima Ahmed)": "Halkan ku qor magaca (tusaale: Xaliimo Axmed)",
    "Draw inside the dark pad below": "Ku sawir farahaaga sanduuqa madow ee hoose",
    "Reset Canvas": "Nadiifi Pad-ka",
    "Party B (Grantee / Client)": "Dhinaca B (Qaataha / Macmiilka)",
    "Property Code / Identifier": "Koodhka Hantida / Aqoonsiga",
    "Property Name / Core Title *": "Magaca Hantida / Cinwaanka rasmiga ah *",
    "Category Range": "Qaybta Hantida",
    "Structure Form (Apartment, Land Plot, etc)": "Qaabka Dhismaha (Abaartamaan, Dhul banaan, jb)",
    "Metropolis City *": "Magaalada Weyn *",
    "Administrative District": "Degmada",
    "Exchange Valuation Price ({currency}) *": "Qiimaha Sarrifka / Kal-qiimeynta *",
    "Payment Instalments / Terms Description": "Cadadka Qaybaha Lacag-bixinta/Shuruudaha",
    "Covenant Stipulations *": "Shuruudaha iyo Qaybaha Heshiiska *",
    "Vehicle ID / Chassis Ref": "Aqoonsiga Gaadhiga / Chassis Ref",
    "Automobile Manufacturer (Make) *": "Shirkadda Sameysay Gaadhiga *",
    "Model Name *": "Nooca / Model-ka Gaadhiga *",
    "Production Year": "Sannadka la Sameeyey",
    "Official License Plate *": "Lambarka Taargada Rasmiga ah *",
    "Agreed Car Valuation Price ({currency}) *": "Qiimaha Gaadhiga Lagu Heshiiyey *",
    "Broker Commission Terms & Compensations *": "Shuruudaha iyo Cadadka Guddiga Dillaalka *",
    "e.g. Abdirahman Yusuf": "tusaale: Cabdiraxmaan Yuusuf",
    "e.g. Halima Ahmed": "tusaale: Xaliimo Axmed",
    "e.g. +252 61 5XXXXXX": "tusaale: +252 61 5XXXXXX",
    "e.g. +252 61 7XXXXXX": "tusaale: +252 61 7XXXXXX",
    "e.g. partyA@example.com": "tusaale: partyA@gmail.com",
    "e.g. partyB@example.com": "tusaale: partyB@gmail.com",
    "e.g. NID-842719": "tusaale: AQ-842719",
    "e.g. NID-108259": "tusaale: AQ-108259",
    "e.g. Mogadishu Airport Zone, Wadajir, Somalia": "tusaale: Ex-giraangirta, Wadajir, Muqdisho, Soomaaliya",
    "e.g. Hodan District, Mogadishu, Somalia": "tusaale: Degmada Hodan, Muqdisho, Soomaaliya",
    "e.g. AP-94021": "tusaale: AP-94021",
    "e.g. Luxury Penthouse Suite B-2": "tusaale: Fillo Qurxoon B-2",
    "e.g. Duplex Villa": "tusaale: Fillo laba dabaq ah",
    "e.g. Mogadishu": "tusaale: Muqdisho",
    "e.g. Hodan": "tusaale: Hodan",
    "e.g. 185000": "tusaale: 185000",
    "e.g. 30% Down, 70% Bank Escrow Transfer": "tusaale: 30% hormaris, 70% bangiga",
    "e.g. CHASSIS-N028741": "tusaale: CHASSIS-N028741",
    "e.g. Toyota": "tusaale: Toyota",
    "e.g. Land Cruiser": "tusaale: Land Cruiser",
    "e.g. JUBALAND-840": "tusaale: TR-840",
    "e.g. 52000": "tusaale: 52000",
    "Provide description of broker duties, affiliated real estate listings, payment percentages, and conditional terms...": "Fahfaahin ka bixi waajibaadka dillaalka, guryaha lala xiriiriyay, boqolleyda lacagta, iyo shuruudaha heshiiska...",
    "Cancel": "Ka Noqo",
    "Preview Agreement": "Horay-u-eeg Heshiiska",
    "Download QR Code": "La-soo-deg QR Code-ka",
    "Submit for Approval": "Gudbi si loo Ansixiyo",
    "Back to Edit": "Ku Noqo Dejinta",
    "Print": "Daabac",
    "Download PDF": "La-soo-deg PDF",
    "Verification Constraints Required:": "Shuruudaha Xaqiijinta ee loo baahan yahay:",
    "Submitted Successfully": "Si Guul leh ayaa loo Gudbiyey",
    "Status: Pending Approval": "Xaaladda: Ansixis Sugaya",
    "System Record Registered": "Diiwaanka Nidaamka waa la Diiwaangeliyey",
    "Agreement Record ID": "Aqoonsiga Diiwaanka Heshiiska",
    "Audit Track Status": "Xaaladda Hubinta Hantidhawrka",
    "Pending Officer Review": "Dib-u-eegis Sugaya",
    "Your legal agreement documents have been logged securely. You can direct the municipal administration division or real estate desk in charge of verification to sign off using the administrator console.": "Dukumentiyadaada heshiiska sharci si sugan ayaa loo diiwaangeliyey. Waxaad ku hagi kartaa qaybta maamulka dowladda hoose ama xafiiska guryaha ee xaqiijinta u qaabilsan inay ku ansixiyaan console-ka maamulaha.",
    "Go to Dashboard": "Aad Pankeeyga",
    "Draft Another Agreement": "Qor Heshiis Kale",
    "Cursive Representation": "Saxeexa Farta Cursive",
    "Vectored path captured. Ready to bind.": "Saxeexii waa la duubay. Waa diyaar.",
    "DRAFT DOCUMENT - PREVIEW STATE": "QABYO-QORAAL - HORAY-U-EEG HESHIISKA",
    "LEDGER REGISTRY DEED": "DIIWAANKA GUUD EE SHARCIGA",
    "Provisional Draft": "Kumeelgaadh",
    "Witnessed & Logged on the secure AmaanEstate Administrative Grid on:": "Waxaa lagu marag-furay oo lagu diiwaangeliyey Grid-ka maamulka ee AmaanEstate:",
    "I. Contract Category Specifications": "I. Tilmaamaha Qaybta Heshiiska",
    "Deed Scheme Type:": "Nooca Sanduuqa Heshiiska:",
    "Current Valuation Total:": "Wadarta Qiimaha Guud:",
    "II. Contracting Sovereign Parties": "II. Dhinacyada Heshiiska Saxeexaya",
    "PARTY A (Grantor/Seller)": "DHINACA A (Bixiyaha/Mulkiilaha/Iibiyaha)",
    "PARTY B (Grantee/Client)": "DHINACA B (Qaataha/Macmiilka)",
    "Name:": "Magaca:",
    "Phone:": "Taleefanka:",
    "Email:": "Imeelka:",
    "Registry ID No:": "Lambarka Aqoonsiga:",
    "Domicile:": "Cinwaanka:",
    "III. Object Asset Specifications": "III. Tilmaamaha Hantida lagu Heshiiyey",
    "Property Unique ID:": "ID-ga Gaarka ah ee Hantida:",
    "Property Title/Lodge:": "Cinwaanka Hantida:",
    "Covenant Status:": "Xaaladda Qodobbada:",
    "Structure Specification:": "Nooca Dhismaha:",
    "Metropolis City:": "Magaalada Weyn:",
    "District Address:": "Degmada:",
    "Vehicle Tracker No:": "Lambarka Raadraaca Gaadhiga:",
    "Automobile Maker:": "Warshada Sameysay:",
    "Model / Specific:": "Nooca / Model-ka:",
    "Manufacturing Year:": "Sannadka la Sameeyey:",
    "Registration Plate:": "Taargada Gaadhiga:",
    "IV. General Legal Covenants & Assurances": "IV. Shuruudaha Guud ee Sharciga & Ballanqaadyada",
    "V. Binding Endorsements & Proof of Intent": "V. Saxeexyada Adag & Caddeynta Damaca",
    "PARTY A SIGNATURE": "SAXEEXA DHINACA A",
    "PARTY B SIGNATURE": "SAXEEXA DHINACA B",
    "Blank Drawn Signature": "Saxeex Sawiran oo Madhan",
    "VI. Digital Registry Ledger Verification": "VI. Hubinta Diiwaanka Dhijitaalka ah ee QR Code",
    "Deed Record ID:": "Aqoonsiga Diiwaanka:",
    "Contract Number:": "Lambarka Heshiiska:",
    "Registered Date:": "Taariikhda la Diiwaangeliyey:",
    "Verification Scheme:": "Habka Hubinta:",
    "AmaanEstate Secured Cryptographic Ledger": "Diiwaanka Hubinta Sugan ee AmaanEstate",
    "Provisional Registry (Pending Approval)": "Diiwaangelinta Kumeelgaadhka ah (Ansixis Sugaya)",
    "Agreement Title is required.": "Cinwaanka Heshiiska waa khasab.",
    "Party A (Seller/Owner) Full Name is required.": "Magaca dhammaystiran ee Dhinaca A waa khasab.",
    "Party A Contact Phone is required.": "Taleefanka Dhinaca A waa khasab.",
    "Party B (Buyer/Tenant) Full Name is required.": "Magaca dhammaystiran ee Dhinaca B waa khasab.",
    "Party B Contact Phone is required.": "Taleefanka Dhinaca B waa khasab.",
    "Property Name/Title is required.": "Magaca/Cinwaanka Hantida waa khasab.",
    "Property City is required.": "Magaalada Hantidu ku taallo waa khasab.",
    "A valid property valuation price is required.": "Qiimaha hantida ee saxda ah waa khasab.",
    "Vehicle Automobile Make and Model are required.": "Warshada iyo Nooca gaadhiga waa khasab.",
    "Vehicle License Plate is required.": "Taargada gaadhiga waa khasab.",
    "A valid vehicle transaction price is required.": "Qiimaha saxda ah ee gaadhiga waa khasab.",
    "Broker Details / Commission Terms cannot be blank.": "Faahfaahinta / Shuruudaha dillaalka ma noqon karaan kuwo madhan.",
    "Party A must type in their binding signature name.": "Dhinaca A waa inuu ku qoraa magaca saxeexa ee khasabka ah.",
    "Party B must type in their binding signature name.": "Dhinaca B waa inuu ku qoraa magaca saxeexa ee khasabka ah.",
    "Review and alter standard legal protections directly inside the document. Ensure exact payment deadlines and breach guidelines are specified according to local commerce bylaws.": "Fahm oo wax ka bedel nidaamka heshiisyada sharciga ah ee caadiga ah. Hubi in jadwalka lacag bixinta iyo ciqaabta la qeexay."
  }
};

type Language = 'en' | 'so';
type Currency = 'ETB' | 'USD';

interface SettingsContextType {
  language: Language;
  currency: Currency;
  setLanguage: (lang: Language) => void;
  setCurrency: (curr: Currency) => void;
  t: (key: string) => string;
}

const SettingsContext = createContext<SettingsContextType | null>(null);

export function SettingsProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    try {
      return (localStorage.getItem('amaan_language') as Language) || 'en';
    } catch (e) {
      console.warn("Storage access failed:", e);
      return 'en';
    }
  });
  
  const [currency, setCurrency] = useState<Currency>(() => {
    try {
      return (localStorage.getItem('amaan_currency') as Currency) || 'ETB';
    } catch (e) {
      console.warn("Storage access failed:", e);
      return 'ETB';
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem('amaan_language', language);
    } catch (e) {
      console.warn("Storage write failed:", e);
    }
  }, [language]);

  useEffect(() => {
    try {
      localStorage.setItem('amaan_currency', currency);
    } catch (e) {
      console.warn("Storage write failed:", e);
    }
  }, [currency]);

  const t = (key: string) => {
    return (translations[language] as Record<string, string>)[key] || key;
  };

  return (
    <SettingsContext.Provider value={{ language, currency, setLanguage, setCurrency, t }}>
      {children}
    </SettingsContext.Provider>
  );
}

export function useSettings() {
  const context = useContext(SettingsContext);
  if (!context) {
    throw new Error('useSettings must be used within SettingsProvider');
  }
  return context;
}
